config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  #
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  %w(404 422 500 503).each do |code|
    get code, to: 'errors#show', code: code
  end

  root to: 'home#index'

  resources :categories, only: [:show]

  resources :institutions,                only: [:show] do
    resources :documents,                 only: [:show] do
      member do
        get :download
      end
    end
    resources :remunerations,             only: [:index]
    resources :selections,                only: [:index]
    resources :inventories,               only: [:index, :show]
    resources :officials,                 only: [:index, :show]
    resources :consultants,               only: [:index, :show]
    resources :travels,                   only: [:index, :show]
    resources :services,                  only: [:index, :show]
    resources :privates,                  only: [:index, :show]
    resources :executing_works,           only: [:index, :show]
    resources :contracts,                 only: [:index, :show]
    resources :recruitment_results,       only: [:index, :show]
    resources :participation_mechanisms,  only: [:index, :show]
  end

  namespace :panel do
    root to: 'activity_logs#index'
    get "institution_logs" => "activity_logs#institution_logs", as: :institution_logs

    resources :activity_logs, only: [:index, :show]
    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :recycler_docks, only: [:index, :show] do
      get :restore, on: :member
    end

    [
      :oir_addresses,
      :institution_types,
      :institutions,
      :institution_dependencies,
      :executing_works,
      :standard_categories,
      :document_categories,
      :information_standard_frames,
      :information_standards,
      :travels,
      :committees,
      :officials,
      :consultants,
      :budgetary_units,
      :services_categories,
      :services,
      :service_steps,
      :work_lines,
      :remunerations,
      :admins,
      :institution_items,
      :procurements,
      :institution_recruitment_results,
      :resources_to_private_recipients,
      :participation_mechanisms,
      :institution_confidential_infos,
      :passage_payers,
      :viatical_payers,
      :expenses_payers,
      :disclaimers,
      :execution_phases
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end

    resources :statistics, only: [:index] do
      post :standards_downloaded, on: :collection
      post :documents_downloaded, on: :collection
    end

    resources :documents do
      get :information_standard_document_categories, on: :collection
      put :updates, on: :collection
      put :destroys, on: :collection
      get :list, on: :collection
    end

    namespace :grid do
      [
        :oir_addresses,
        :institution_types,
        :institutions,
        :institution_dependencies,
        :executing_works,
        :standard_categories,
        :document_categories,
        :information_standard_frames,
        :information_standards,
        :travels,
        :committees,
        :officials,
        :consultants,
        :documents,
        :budgetary_units,
        :services_categories,
        :services,
        :service_steps,
        :work_lines,
        :remunerations,
        :admins,
        :institution_inventory_categories,
        :institution_items,
        :procurements,
        :institution_recruitment_results,
        :institution_confidential_infos,
        :resources_to_private_recipients,
        :participation_mechanisms
      ].each do |resource|
        resources resource, only: [:index, :new, :create]
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :home, only: [:index]
      resources :institution_types, only: [:index]
      resources :institutions, only: [:index]
      resources :standard_categories, only: [:index]
      resources :information_standards, only: [:index]
      resources :information_standard_frames, only: [:index]
      resources :consultants, only: [:index]
      resources :committees, only: [:index]
      resources :budgetary_units, only: [:index]
      resources :dependencies, only: [:index]
      resources :disclaimers, only: [:index]
      resources :document_categories, only: [:index] #
      resources :documents, only: [:index]           #
      resources :executing_works, only: [:index]
      resources :inventories, only: [:index]
      resources :officials, only: [:index]
      resources :participation_mechanisms, only: [:index] #
      resources :privates, only: [:index]
      #resources :recruitment_results, only: [:index] #
      resources :remunerations, only: [:index]
      resources :services_categories, only: [:index]
      resources :services, only: [:index]
      resources :service_steps, only: [:index]
      resources :travels, only: [:index]
      resources :documents, only: [:index]
      resources :document_categories, only: [:index]
    end
  end

  get 'search', to: 'home#search'
end

app/controllers/api/v1/home_controller.rb
class Api::V1::HomeController < ApplicationController
  def index
    add_breadcrumb 'Inicio', root_url
    add_breadcrumb 'API'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
#
class HomeController < ApplicationController
  def index
    @institution_types = InstitutionType.enabled
    @institutions_count = Institution.enabled.count
    @services_count = Service.enabled.count
    @documents_count = Document.enabled.count
    total_registers = Consultant.where(enabled: true).count +
      Procurement.where(enabled: true).count +
      Official.where(enabled: true).count +
      Committee.count +
      InstitutionItem.where(enabled: true).count +
      ParticipationMechanism.where(enabled: true).count +
      ExecutingWork.where(enabled: true).count +
      ResourcesToPrivateRecipient.where(enabled: true).count +
      Remuneration.where(enabled: true).count +
      InstitutionRecruitmentResult.where(enabled: true).count +
      Service.where(enabled: true).count +
      Travel.where(enabled: true).count
    @total_count = @documents_count + total_registers
    @documents_download = Document.enabled.sum(:downloads)
    @last_update = Document.enabled.select(:updated_at).reorder(updated_at: :desc).limit(1).first
    @featured_resolutions = Document.featured_resolutions
    render layout: false
  end

  def search
    @results = PgSearch.multisearch(params[:ft]).includes(:searchable).paginate(:page => params[:page], :per_page => 10)
  end
end

app/views/home/index.haml
!!! 5
%html{ lang: I18n.locale }
  %head
    = display_meta_tags
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui' }
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }

    -# = display_meta_tags

    %link{ href: image_path('favicon.png'), sizes: '128x128', rel: 'shortcut icon' }
    %link{ href: image_path('favicon.png'), sizes: '128x128', rel: 'apple-touch-icon' }
    %link{ href: image_path('favicon.png'), sizes: '128x128', rel: 'apple-touch-icon-precomposed' }

    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    = render partial: 'layouts/application/analytics'
  %body
    .header
      .row
        .columns.small-0.medium-0.large-3.small-order-3.medium-order-3.large-order-1
        .columns.small-24.medium-24.large-18.small-order-2.medium-order-2.large-order-2
          = image_tag 'transparencia-sv.png'
          %h1
            transparencia.gob.sv
          %h2
            Consulte información pública de #{@institutions_count} instituciones y más de #{number_with_delimiter(@total_count)}
            documentos y registros
        .columns.small-24.medium-24.large-3.small-order-1.medium-order-1.large-order-3
          .menu
            = link_to 'API', api_v1_home_index_url
            = mail_to 'info@gobiernoabierto.gob.sv' do
              = image_tag('icon-mail.png')

      .row.align-center
        .columns.small-24.medium-12.large-8
          = form_tag(search_url, method: :get) do
            = search_field_tag 'ft', params[:ft], placeholder: 'Buscar'
            = button_tag type: :submit, name: nil do
              = image_tag 'icon-search.png'

      .row.align-center
        .columns.small-24.medium-24.large-16
          .categories
            - @institution_types.each do |institution_type|
              = link_to category_url(institution_type) do
                = institution_type.name
                = " (#{institution_type.how_many?})"

    %main
      .row.align-center#info-
        .columns.small-24.medium-20.large-20
          .container.panel.text-center
            %h2
              Información que puedes consultar


            .row.align-justify.text-center
              .columns.small-24.medium-12.large-6
                = link_to '#', class: 'featured-standard' do
                  = image_tag 'icon-info-documents.png'
                  %strong.number
                    = number_with_delimiter @documents_count
                  Documentos

              - if @last_update
                .columns.small-24.medium-12.large-6
                  = link_to nil, class: 'featured-standard' do
                    = image_tag 'icon-info-updated-at.png'
                    %strong.number
                      = @last_update.updated_at.try(:strftime, '%d/%m/%Y')
                    Última actualización

              .columns.small-24.medium-12.large-6
                = link_to nil, class: 'featured-standard' do
                  = image_tag 'icon-info-downloads.png'
                  %strong.number
                    = number_with_delimiter @documents_download
                  Descargas de documentos

              .columns.small-24.medium-12.large-6
                = link_to nil, class: 'featured-standard' do
                  = image_tag 'icon-info-services.png'
                  %strong.number
                    = number_with_delimiter @services_count
                  Servicios disponibles

      .row.align-center
        .columns.small-24.medium-20.large-20
          .container.panel
            %h2
              Resoluciones de información

            .table
              .row.align-justify.align-middle
                .columns.small-18.medium-18.large-8
                  %strong Institución
                .columns.small-5.medium-4.large-2
                  %strong Descargas
                .columns.small-18.medium-18.large-10
                  %strong Documento
                .columns.small-5.medium-4.large-2
                  %strong Peso
              - @featured_resolutions.each do |r|
                .row.align-justify.align-middle
                  .columns.small-18.medium-18.large-8
                    %strong
                      = r.institution.try(:name)
                  .columns.small-5.medium-4.large-2
                    = r.downloads
                  .columns.small-18.medium-18.large-10
                    -# TODO Enlace para contabilizar descargas
                    = link_to r.document.url do
                      = r.title
                  .columns.small-5.medium-4.large-2
                    = number_to_human_size r.document_file_size

            .row
              .columns.small-24
                .text-center
                  = link_to 'http://www.gobiernoabierto.gob.sv/information_requests/new', class: 'btn', target: '_blank' do
                    Solicite información pública

    = render partial: 'layouts/application/footer'

app/views/home/search.haml
.panel
  %h2
    Resultados de búsqueda: #{params[:ft]}
  - if @results.empty?
    %p
      No hay resultados para su búsqueda
      %strong
        = params[:ft]
- if @results.any?
  .table.spaced
    - @results.each do |r|
      / DOCUMENTOS
      - if r.searchable.is_a?(Document)
        - document = r.searchable
        .row
          .columns.small-24.medium-8.large-4.small-order-1.medium-order-1.large-order-1
            = l document.updated_at, format: :localized2
          .columns.small-24.medium-24.large-12.small-order-2.medium-order-2.large-order-2
            = link_to document.document.url, :target => "_blank" do
              = document.name
          .columns.small-12.medium-8.large-4.small-order-4.medium-order-4.large-order-3
            = "#{document.file_extension} | #{number_to_human_size(document.document.size)}"
          .columns.small-24.medium-24.large-24.small-order-3.medium-order-3.large-order-4
            .text-mutted
              = raw summarized_text(document.description, 22, true)
          .columns.small-24.small-order-5
            = link_to document.institution.try(:name), institution_url(document.institution)
            - if document.information_standard_id.present?
              = '.'
              = render partial: 'institutions/standard_url', locals: {institution: document.institution, standard: document.information_standard} rescue nil

      / SERVICIOS
      - if r.searchable.is_a?(Service)
        - item = r.searchable
        - @institution = item.institution_id
        .row
          .columns.small-12.medium-12.large-4.small-order-1.medium-order-3.large-order-1
            = item.updated_at.strftime("%d/%m/%Y")
          .columns.small-24.medium-24.large-24.small-order-2.medium-order-1.large-order-2
            = link_to institution_service_url(@institution, item) do
              = item.name
          .columns.small-24.medium-24.large-24.small-order-3.medium-order-2.large-order-3
            .text-mutted
              = raw summarized_text("#{item.institution_dependency.nil? ? '' : item.institution_dependency.name.to_s+" » " }" + item.description.to_s, 22, true)
          .columns.small-24.small-order-4
            = link_to item.institution.try(:name), institution_url(item.institution)
            = '.'
            = link_to('Servicios', institution_services_url(item.institution))


  %center
    = will_paginate @results