config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  #
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  %w(404 422 500 503).each do |code|
    get code, to: 'errors#show', code: code
  end

  root to: 'home#index'

  resources :categories, only: [:show]

  resources :institutions,                only: [:show] do
    resources :documents,                 only: [:show] do
      member do
        get :download
      end
    end
    resources :remunerations,             only: [:index]
    resources :selections,                only: [:index]
    resources :inventories,               only: [:index, :show]
    resources :officials,                 only: [:index, :show]
    resources :consultants,               only: [:index, :show]
    resources :travels,                   only: [:index, :show]
    resources :services,                  only: [:index, :show]
    resources :privates,                  only: [:index, :show]
    resources :executing_works,           only: [:index, :show]
    resources :contracts,                 only: [:index, :show]
    resources :recruitment_results,       only: [:index, :show]
    resources :participation_mechanisms,  only: [:index, :show]
  end

  namespace :panel do
    root to: 'activity_logs#index'
    get "institution_logs" => "activity_logs#institution_logs", as: :institution_logs

    resources :activity_logs, only: [:index, :show]
    resources :profile, only: [:edit, :update]
    resources :versions, only: [:show]

    resources :admin_settings, only: [] do
      put :table_columns, on: :collection
    end

    resources :recycler_docks, only: [:index, :show] do
      get :restore, on: :member
    end

    [
      :oir_addresses,
      :institution_types,
      :institutions,
      :institution_dependencies,
      :executing_works,
      :standard_categories,
      :document_categories,
      :information_standard_frames,
      :information_standards,
      :travels,
      :committees,
      :officials,
      :consultants,
      :budgetary_units,
      :services_categories,
      :services,
      :service_steps,
      :work_lines,
      :remunerations,
      :admins,
      :institution_items,
      :procurements,
      :institution_recruitment_results,
      :resources_to_private_recipients,
      :participation_mechanisms,
      :institution_confidential_infos,
      :passage_payers,
      :viatical_payers,
      :expenses_payers,
      :disclaimers,
      :execution_phases
    ].each do |resource|
      resources resource do
        put :updates, on: :collection
        put :destroys, on: :collection
        get :list, on: :collection
      end
    end

    resources :statistics, only: [:index] do
      post :standards_downloaded, on: :collection
      post :documents_downloaded, on: :collection
    end

    resources :documents do
      get :information_standard_document_categories, on: :collection
      put :updates, on: :collection
      put :destroys, on: :collection
      get :list, on: :collection
    end

    namespace :grid do
      [
        :oir_addresses,
        :institution_types,
        :institutions,
        :institution_dependencies,
        :executing_works,
        :standard_categories,
        :document_categories,
        :information_standard_frames,
        :information_standards,
        :travels,
        :committees,
        :officials,
        :consultants,
        :documents,
        :budgetary_units,
        :services_categories,
        :services,
        :service_steps,
        :work_lines,
        :remunerations,
        :admins,
        :institution_inventory_categories,
        :institution_items,
        :procurements,
        :institution_recruitment_results,
        :institution_confidential_infos,
        :resources_to_private_recipients,
        :participation_mechanisms
      ].each do |resource|
        resources resource, only: [:index, :new, :create]
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :home, only: [:index]
      resources :institution_types, only: [:index]
      resources :institutions, only: [:index]
      resources :standard_categories, only: [:index]
      resources :information_standards, only: [:index]
      resources :information_standard_frames, only: [:index]
      resources :consultants, only: [:index]
      resources :committees, only: [:index]
      resources :budgetary_units, only: [:index]
      resources :dependencies, only: [:index]
      resources :disclaimers, only: [:index]
      resources :document_categories, only: [:index] #
      resources :documents, only: [:index]           #
      resources :executing_works, only: [:index]
      resources :inventories, only: [:index]
      resources :officials, only: [:index]
      resources :participation_mechanisms, only: [:index] #
      resources :privates, only: [:index]
      #resources :recruitment_results, only: [:index] #
      resources :remunerations, only: [:index]
      resources :services_categories, only: [:index]
      resources :services, only: [:index]
      resources :service_steps, only: [:index]
      resources :travels, only: [:index]
      resources :documents, only: [:index]
      resources :document_categories, only: [:index]
    end
  end

  get 'search', to: 'home#search'
end

app/models/participation_mechanism.rb
class ParticipationMechanism < ApplicationRecord
  include CsvExportable
  include Versionable
  include Institutionable

  belongs_to :institution
  belongs_to :institution_dependency

  # Validations
  validates :institution_id, presence: true
  validates :name,           presence: true

  scope :enabled, -> { where(enabled: true) }

  has_attached_file :report
  do_not_validate_attachment_file_type :report

  def self.acts_as_label
    :name
  end

  def acts_as_label
    send(self.class.acts_as_label)
  end
end

app/controllers/api/v1/participation_mechanisms_controller.rb
module Api
  module V1
    class ParticipationMechanismsController < TemplateInstitutionParamsController
      def model
        ParticipationMechanism
      end
    end
  end
end

app/controllers/panel/participation_mechanisms_controller.rb
# frozen_string_literal: true
module Panel
  #
  class ParticipationMechanismsController < PanelController
    include Panel::Crud
    include Panel::Multiple
    include Panel::CsvExportable
    #

    def model
      ParticipationMechanism
    end

    def permits
      [:institution_dependency_id, :description, :participation_requirements, :execution_date_begin, :execution_date_end, :objetive, :result, :report, :institution_id, :name, :enabled] 
    end

    def exportable_fields
      [:institution_dependency_id, :description, :participation_requirements, :execution_date_begin, :execution_date_end, :objetive, :result, :report, :institution_id, :name, :enabled] 
    end

    def init_form
      @institutions = policy_scope(Institution)
                         .order(Institution.acts_as_label)

      @institution_dependencies = policy_scope(InstitutionDependency)
                                    .order(InstitutionDependency.acts_as_label)
    end

  end
end

app/controllers/participation_mechanisms_controller.rb
# frozen_string_literal: true
#
class ParticipationMechanismsController < ApplicationController
  include PdfExportable
  include Componentable

  def model
    ParticipationMechanism
  end

  def index
    super
    @disclaimers                                                            = Disclaimer.enabled.where(institution_id: @institution.id, information_standard_id: @information_standard.id)
    params[:q]                                                              = {}
    params[:q][:description_or_participation_requirements_or_objetive_cont] = params[:pm_fields] unless params[:pm_fields].blank?
    @items                                                                  = @items.where("execution_date_begin BETWEEN ? AND ?", Date.new(params[:pm_date].to_i), Date.new(params[:pm_date].to_i).end_of_year) unless params[:pm_date].blank? rescue nil
    @show_form                                                              = @items.count > 0
    @pm_years                                                               = @items.reorder("execution_date_begin ASC").map{|y| y.execution_date_begin.try(:year) }.compact.uniq.delete_if{|y| y.to_i==0}
    @q                                                                      = @items.enabled.search(params[:q])
    @results                                                                = @q.result.order("updated_at DESC").paginate(page: params[:page], :per_page => 20)
  end


  def filters
    super
    @information_standard = InformationStandard.find(Config[:dynamical_information_standards][:participation_mechanisms])
    @mechanism            = ParticipationMechanism.find(params[:id]) if action_name == 'show'
    @document_categories  = DocumentCategory.where("information_standard_id = ? AND institution_id = ?", Config[:dynamical_information_standards][:participation_mechanisms], @institution.id).order("name ASC")

    if @information_standard.priority_order?
      @documents         =  Document.enabled.where(:institution_id => @institution.id, :information_standard_id => Config[:dynamical_information_standards][:participation_mechanisms]).reorder("year DESC, priority DESC")
    else
      @documents         =  Document.enabled.where(:institution_id => @institution.id, :information_standard_id => Config[:dynamical_information_standards][:participation_mechanisms]).order('updated_at desc')
    end

    @years               = @documents.where('year > 0').reorder('year ASC').pluck('DISTINCT CAST(year AS INT)').sort
  rescue
    nil
  end

  def breadcrumb
    super
    add_breadcrumb 'Mecanismos de participación ciudadana', institution_participation_mechanisms_url(@institution)
    add_breadcrumb truncate(@mechanism.name, length: 50),
                   institution_service_url(@institution, @mechanism)
  rescue
    nil
  end

  def exportable_fields
    [:institution_id, :institution_dependency_id, :name, :description,
     :participation_requirements, :objetive, :result]
  end
end

app/views/participation_mechanisms/index.haml
.row.align-center

  .columns.small-24.medium-8.large-6
    = render partial: 'institutions/nav'

  .columns.small-24.medium-15.large-18
    %h1
      = @institution.acronym
      %small
        = @institution.name


    .panel#participation-area
      %h2
        = @information_standard.name
        %p.text-mutted
          = @information_standard.try(:description)

      - unless @disclaimers.empty?
        .disclaimer.callout.callout-warning
          %h2
            Nota(s) aclaratoria(s)
          - @disclaimers.each do |disclaimer|
            .row.align-justify.align-middle.margin-down
              .columns.small-20.medium-8.small-order-1.medium-order-1
                = disclaimer.name
              .columns.small-24.medium-13.small-order-2.medium-order-2
                = disclaimer.description
              .columns.small-4.medium-3.small-order-1.medium-order-3
                = link_to image_tag('icon-download-small-gray.png'), disclaimer.file.url, target: "_blank"

      - if @show_form
        = form_tag(institution_participation_mechanisms_url(params[:institution_id], anchor: 'participation-area'), method: :get, id: "officials") do
          = render partial: "layouts/documents/documents_hidden_fields"
          .filters
            .row.align-justify.align-middle
              .columns.small-20.flex
                = text_field_tag "pm_fields", nil, placeholder: 'Buscar en listado de mecanismos de participación', value: params[:pm_fields]
              .columns.small-4.flex
                = button_tag "Buscar", class: "btn"
              .columns.small-24.medium-11.flex
                = select_tag "pm_date", options_for_select(@pm_years, :selected => params[:pm_date]), include_blank: "-- Todos los años --"
              .columns.small-24.medium-11.flex
                = select_tag "pm_institution_dependency_id", options_for_select(@dependencies.collect{|p| [ p.name, p.id ] }, selected: params[:pm_institution_dependency_id]), { include_blank: "-- Todas las dependencias --" } rescue nil
        - if @results && @results.size > 0
          .table.spaced.spaced-columns.responsive
            .row.align-justify
              .columns.large-8
                %strong Descripción
              .columns.large-8
                %strong Requisitos de participación
              .columns.large-8
                %strong Resultado
            - @results.each do |item|
              .row.align-justify.align-middle
                .columns.large-8
                  = link_to institution_participation_mechanism_url(@institution, item) do
                    = item.description
                .columns.large-8
                  = raw summarized_text(item.participation_requirements, 22, false) rescue " "
                .columns.large-8
                  = raw summarized_text(item.objetive, 22, false) rescue " "
                .columns.small-24.medium-24
                  .text-mutted
                    = "Creación: " + l(item.created_at, format: :localized2) rescue ""
                    %br
                    = "Actualización: " + l(item.updated_at, format: :localized2) rescue ""
          = will_paginate @results
        - else
          %h2
            No se encontraron resultados

    = render partial: "layouts/documents/document", locals: { years: @years,
      documents: @documents, doc_items: @doc_items,
      url: institution_participation_mechanisms_url(params[:institution_id], anchor: 'documents-area'),
      document_categories: @document_categories }

app/views/participation_mechanisms/show.haml
.row.align-center

  .columns.small-24.medium-8.large-6
    = render partial: 'institutions/nav'

  .columns.small-24.medium-15.large-18
    %h1
      = @institution.acronym
      %small
        = @institution.name

    = link_to 'Regresar al listado', institution_participation_mechanisms_url(@institution), class: 'back float-left'
    = link_to institution_participation_mechanism_url(@institution, @mechanism, format: :pdf), class: "back float-right", title: "Exportar a PDF" do
      = image_tag 'icon-pdf.png'
      Vista en PDF
    .clearfix

    .panel
      %h2
        = "Detalle del mecanismo de participación"

      .table.no-border.no-margin
        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Nombre
          .columns.small-24.medium-17.large-17
            = @mechanism.name

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Descripción
          .columns.small-24.medium-17.large-17
            = @mechanism.description
        - unless @mechanism.institution_dependency_id.blank?
          .row.align-justify
            .columns.small-24.medium-7.large-6
              %strong Dependencia
            .columns.small-24.medium-16.large-17
              = @mechanism.institution_dependency.name rescue nil

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Fecha de inicio de ejecución
          .columns.small-24.medium-17.large-17
            = l @mechanism.execution_date_begin, format: :long

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Fecha de fin de ejecución
          .columns.small-24.medium-17.large-17
            = l @mechanism.execution_date_end, format: :long

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Requisitos de participación
          .columns.small-24.medium-17.large-17
            = @mechanism.participation_requirements

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Objetivo
          .columns.small-24.medium-17.large-17
            = @mechanism.objetive

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Resultado
          .columns.small-24.medium-17.large-17
            = @mechanism.result
        - if @mechanism.report.exists?
          .row.align-justify
            .columns.small-24.medium-6.large-6
              %strong Informe
            .columns.small-24.medium-17.large-17
              = link_to "Adjunto", @mechanism.report.url, target: "_blank"

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Fecha de creación
          .columns.small-24.medium-17.large-17
            = l @mechanism.created_at, format: :localized2

        .row.align-justify
          .columns.small-24.medium-6.large-6
            %strong Fecha de última actualización
          .columns.small-24.medium-17.large-17
            = l @mechanism.created_at, format: :localized2

    = link_to 'Regresar al listado', institution_participation_mechanisms_url(@institution), class: 'back'